steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x ./script.sh
        ./shell.sh
  - name: 'python:3.9'
    entrypoint: python3.9
    args:
      - '-m'
      - pip
      - install
      - google-cloud-secret-manager
      - google-cloud-storage
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-api-python-client
      - -t
      - './lib'
  - name: 'python:3.9'
    entrypoint: python3.9
    env:
      - 'PYTHONPATH=/workspace/lib'
    args: ['./python.py']   
options:
  logging: CLOUD_LOGGING_ONLY